name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
          pip install pytest ruff mypy types-aiofiles types-tqdm
      - name: Ruff
        run: ruff check .
        continue-on-error: true
      - name: Mypy
        run: mypy src
        continue-on-error: true
      - name: Test
        run: pytest -q

